// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKWkVoriPRSSwWZEoPltx0lntJL2VjZZw',
    appId: '1:162868168380:web:710440279c181e50f9b2b9',
    messagingSenderId: '162868168380',
    projectId: 'mymind-s',
    authDomain: 'mymind-s.firebaseapp.com',
    storageBucket: 'mymind-s.firebasestorage.app',
    measurementId: 'G-F967EBYV9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgvILUM5ffG7gdNzCnesNSwOMe-iQ3-TI',
    appId: '1:162868168380:android:f4ef4fdc65a6b0d0f9b2b9',
    messagingSenderId: '162868168380',
    projectId: 'mymind-s',
    storageBucket: 'mymind-s.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkAeEYlxs5lg6xuWv5eWkjcLWSeIL275c',
    appId: '1:162868168380:ios:9ea19d764de8f55ef9b2b9',
    messagingSenderId: '162868168380',
    projectId: 'mymind-s',
    storageBucket: 'mymind-s.firebasestorage.app',
    iosBundleId: 'com.example.mindmapping',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkAeEYlxs5lg6xuWv5eWkjcLWSeIL275c',
    appId: '1:162868168380:ios:9ea19d764de8f55ef9b2b9',
    messagingSenderId: '162868168380',
    projectId: 'mymind-s',
    storageBucket: 'mymind-s.firebasestorage.app',
    iosBundleId: 'com.example.mindmapping',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKWkVoriPRSSwWZEoPltx0lntJL2VjZZw',
    appId: '1:162868168380:web:3193b00e5de17c02f9b2b9',
    messagingSenderId: '162868168380',
    projectId: 'mymind-s',
    authDomain: 'mymind-s.firebaseapp.com',
    storageBucket: 'mymind-s.firebasestorage.app',
    measurementId: 'G-P230TGKNKM',
  );
}
